"""empty message

Revision ID: 50cc2248d9d2
Revises: 1bf7841ca3a2
Create Date: 2024-06-17 18:15:08.020464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50cc2248d9d2'
down_revision = '1bf7841ca3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('cover_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cover_id'], ['covers.id'], name=op.f('fk_books_cover_id_covers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    op.drop_table('boоks')
    with op.batch_alter_table('book_genre', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_genre_book_id_books', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_book_genre_book_id_books'), 'books', ['book_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_book_id_books', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_book_id_books'), 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_book_id_books', 'boоks', ['book_id'], ['id'])

    with op.batch_alter_table('book_genre', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_book_genre_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key('fk_book_genre_book_id_books', 'boоks', ['book_id'], ['id'])

    op.create_table('boоks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('publisher', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('pages', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cover_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cover_id'], ['covers.id'], name='fk_books_cover_id_covers'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('books')
    # ### end Alembic commands ###
